### ISSUE TITLE
关于isCloudEnv的一点想法

### ISSUE THREAD

**Issue by Aben** [dexteryy/webcube#1]
我觉得没必要再引入`NODE_ENV='cloud'`这个变量，因为静态资源文件配置单独的域名已经很普及了，第三方开源库都默认用 `NODE_ENV='production'`区分开发/生产环境，这样就冲突了。我认为用`isProductionEnv &&  process.env.WEBCUBE_DEPLOY_STATIC_ROOT`更合理一些。

```js
//-----webpack.default.config.babel.js----
const getPublicPath = () => {
  if (isProductionEnv) {
    if (process.env.WEBCUBE_DEPLOY_STATIC_ROOT) {
      return process.env.WEBCUBE_DEPLOY_STATIC_ROOT;
    } else {
      return process.env.WEBCUBE_STATIC_ROOT;
    }
  } else {
    return '/static-for-dev/'
  }
}

publicPath: getPublicPath(),
```

**Comment by dexteryy** [comment]
@Aben  抱歉之前没看到-_-b

这个`NODE_ENV='cloud'`我也一直觉得别扭，下次提交时会把它去掉

**Comment by dexteryy** [comment]
之前使用 `NODE_ENV='cloud'` 的地方，现在都可以替换成 `DEPLOY_MODE=staticweb NODE_ENV=production`

之所以引入DEPLOY_MODE，一方面是为之前支持 server-side rendering 和 electron/cordova 的部署方式做准备，一方面是因为 WEBCUBE_DEPLOY_STATIC_ROOT 适合作为静态的设置选项始终放在 env.config 里，同时又需要支持用 `NODE_ENV=production npm run build` 在本地环境里测试产品环境的构建结果（代码压缩、文件名里的 hash 版本……）
