### ISSUE TITLE
可否自定义loaders和babelLoaderPlugins？

### ISSUE THREAD

**Issue by Aben** [dexteryy/webcube#2]
添加一个`customConfig.babelLoaderPlugins`字段？

`loaders`我想到的是利用对象来实现自定义：
```js
const loaders = Object.assign({
   jsx: { test: /\.jsx?$/, ...}
   css: {test: /\.css$/, ...}
}, customConfig.loaders)

module: {
  loaders: Object.values(loaders)
}
```

我实际遇到的问题是：

1. 项目中有用到m4a文件；
2. 我想用[lodash-webpack-plugin](https://github.com/lodash/lodash-webpack-plugin)，`redux-actions`用到了`lodash`，项目中`lodash-webpack-plugin`可以把`lodash`的引用从100KB的减少到18KB，在`webcube-example`里面也减少到45KB左右。

**Comment by dexteryy** [comment]
@Aben 抱歉又没看到……

之前已经可以自定义 webpack plugin，方法是在应用项目里添加`configs/webpack.config.babel.js`，内容是一个这样的 JSON：https://github.com/dexteryy/webcube-example/blob/master/configs/webpack.config.babel.js

0.5.9 [新增加](https://github.com/dexteryy/webcube/blob/0.5.9/src/configs/webpack.default.config.babel.js#L21)了几个可自定义的 webpack 配置，包括 [babel-loader 的 plugin](https://github.com/dexteryy/webcube/blob/0.5.9/src/configs/webpack.default.config.babel.js#L200)，应该可以满足你这个需求…

**Comment by Aben** [comment]
@dexteryy 赞，新增加的自定义字段终于让我不用修改webcube源码直接使用了。

还有就是webpack loaders不能扩充，某项目中用到了m4a格式的文件，当然这有点吹毛求疵了，可以换成mp3格式的解决。

总体上这个starter kit已经很赞了，我很满意；）
